### ISSUE TITLE
RTMP version seems not to work

### ISSUE THREAD

**Issue by domfaber** [aws-solutions/live-streaming-on-aws-with-mediastore#12]
**Describe the bug**
When I launch the stack with RTMP the demo is not showing. Also I'm not able to stream from OBS to the input. 

**To Reproduce**
Deploy with RTMP and CIDR 0.0.0.0/0

**Expected behavior**
I expected that at least the demo would work. Connecting with OBS seems to work but there is no output. 

**Please complete the following information about the solution:**
- [2.1.0] Version: [e.g. v1.0.0]
- [ eu-central-1] Region: [e.g. us-east-1]
- [ no] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by eggoynes** [comment]
Hi @domfaber 

Thank you for using our Live Streaming on AWS with MediaStore solution. Make sure the AWS MediaLive channel you have is started. We recently updated this solution to default to not starting on AWS MediaLive channel on launch, this is to save cost by running the AWS MediaLive channel only when needed. 

When launching the solution make sure to set the **Start MediaLive Channel** to yes on launch. 
![image](https://user-images.githubusercontent.com/40248820/143087652-c95830e3-9ae0-4a7d-a7d6-1b51de46c711.png)

Lastly if you have already launched this solution just head on over to the AWS MediaLive console, click the MediaLive channel that was created, and there should be a button the start the AWS MediaLive channel. 

I hope that helps. Please reopen this ticket if that doesn't solve your problem.

**Comment by domfaber** [comment]
Thanks for your fast reply. Unfortunately I started the channel and I also can connect with OBS. But I'm not able to view the stream. I'm using the LiveStreamUrl provided under outputs and entered this in a HLS player.

**Comment by eggoynes** [comment]
Hi @domfaber 

Let me check a few things. I launched this with the default name, and used 0.0.0.0/0 like you mentioned for the input CIDR. 
This is working for me in OBS when streaming my desktop. Does that match? I used the default name of the solution. 

![image](https://user-images.githubusercontent.com/40248820/143098831-c7a54016-b641-49c6-bd8a-b1b902cdd80d.png)

**Comment by domfaber** [comment]
I did the same now. And I can stream from OBS. But I still can't receive it when I open this link in a player: https://d1ux8kt61rvsa5.cloudfront.net/stream/index.m3u8 
Can you open it?

**Comment by domfaber** [comment]
Ok, I tested with another player, and it worked. Used a chrome extension which didn't work. Sorry to bother you with this. And many thanks for your help!
